# Generated by Django 4.2.21 on 2025-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.CharField(max_length=10)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('directors', models.TextField()),
                ('cast', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
