# Generated by Django 4.2.21 on 2025-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_rename_rating_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'release_year')},
        ),
    ]
