# Generated by Django 4.2.21 on 2025-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_title_alter_movie_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='MoviePerson',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
